/// Classifies an arbitrary SQL statement as read-only or writing.
///
/// This is an **allow-list**: only statements we can positively recognise as
/// read-only are `Read`; everything else — including anything we fail to parse
/// — is `Write`. A deny-list ("does it contain INSERT?") fails *open*: every
/// Postgres release adds statements, and one missed entry is an unguarded write
/// to a production database. An allow-list fails *closed*: the worst case is a
/// legitimate SELECT being refused, which the user immediately sees and can
/// resolve by granting the 10-minute window.
///
/// The SQL here is generated by an LLM which may itself have read attacker-
/// controlled table contents, so it is treated as untrusted input.
///
/// **This is a UX guardrail, not a security boundary.** A string classifier
/// cannot know what a called function's body does (see `SIDE_EFFECT_FUNCTIONS`),
/// so it can never be airtight. The real boundary is a least-privileged Postgres
/// role on the connection string.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SqlKind {
    Read,
    Write { reason: String },
}

impl SqlKind {
    pub fn is_write(&self) -> bool {
        matches!(self, Self::Write { .. })
    }

    fn write(reason: impl Into<String>) -> Self {
        Self::Write {
            reason: reason.into(),
        }
    }
}

/// Statements that modify data or schema, mapped to the wording we hand back to
/// the LLM. This list exists purely for good error messages — an unrecognised
/// statement is refused anyway by the allow-list, so a gap here costs clarity,
/// never safety.
fn describe_write_statement(head: &str) -> Option<&'static str> {
    let text = match head {
        "insert" => "INSERT writes rows",
        "update" => "UPDATE modifies rows",
        "delete" => "DELETE removes rows",
        "merge" => "MERGE writes rows",
        "truncate" => "TRUNCATE empties a table",
        "drop" => "DROP removes a database object",
        "create" => "CREATE adds a database object",
        "alter" => "ALTER changes a database object",
        "grant" => "GRANT changes privileges",
        "revoke" => "REVOKE changes privileges",
        "copy" => "COPY reads or writes files/tables outside a plain query",
        "call" => "CALL runs a procedure, which may write and commit",
        "do" => "DO runs an arbitrary procedural block",
        "vacuum" => "VACUUM rewrites table storage",
        "analyze" => "ANALYZE rewrites planner statistics",
        "reindex" => "REINDEX rebuilds indexes",
        "cluster" => "CLUSTER rewrites table storage",
        "refresh" => "REFRESH MATERIALIZED VIEW rewrites a materialized view",
        "comment" => "COMMENT changes catalog metadata",
        "lock" => "LOCK takes explicit locks",
        "checkpoint" => "CHECKPOINT forces a write to disk",
        "notify" | "listen" | "unlisten" => "NOTIFY/LISTEN changes session state",
        "prepare" => "PREPARE can stage a write for later EXECUTE",
        "execute" => "EXECUTE can run a previously prepared write",
        "deallocate" => "DEALLOCATE changes session state",
        "declare" | "fetch" | "move" | "close" => {
            "cursor statements leave state on a pooled connection"
        }
        "begin" | "start" | "commit" | "rollback" | "savepoint" | "release" | "abort" | "end" => {
            "transaction control leaves state on a pooled connection"
        }
        "set" | "reset" => "SET/RESET changes session state on a pooled connection",
        "discard" => "DISCARD changes session state",
        "load" => "LOAD loads a shared library",
        "import" => "IMPORT FOREIGN SCHEMA creates objects",
        "security" => "SECURITY LABEL changes catalog metadata",
        "reassign" => "REASSIGN OWNED changes ownership",
        _ => return None,
    };
    Some(text)
}

/// Functions that write or reach outside the database even when called from a
/// plain `SELECT`. Best-effort defence-in-depth: a deny-list *inside* the
/// allow-list, and therefore incomplete by nature — a user-defined function
/// wrapping any of these is invisible from the call site.
const SIDE_EFFECT_FUNCTIONS: &[&str] = &[
    "nextval",
    "setval",
    "pg_read_file",
    "pg_read_binary_file",
    "pg_ls_dir",
    "pg_stat_file",
    "lo_import",
    "lo_export",
    "dblink",
    "dblink_exec",
    "pg_terminate_backend",
    "pg_cancel_backend",
    "pg_logical_emit_message",
    "pg_create_physical_replication_slot",
    "pg_drop_replication_slot",
];

/// Statements that modify data wherever they appear — including nested inside a
/// CTE, which is the classic `WITH x AS (INSERT ... RETURNING *) SELECT * FROM x`
/// bypass.
const DATA_MODIFYING: &[&str] = &["insert", "update", "delete", "merge"];

/// Words that veto a read if they appear **anywhere** in the raw SQL — including
/// inside string literals, quoted identifiers and comments.
///
/// This is deliberately blunt and over-blocks: `SELECT * FROM audit WHERE action
/// = 'insert'` needs the write window even though it plainly only reads. That is
/// the intended trade — the rule is meant to be predictable ("if it says insert,
/// click the button") rather than clever, and it keeps a bug in the tokenizer
/// from turning into an unguarded write.
///
/// Membership is chosen carefully. A word belongs here only if it never occurs
/// in read syntax:
/// - `end` is excluded — it would refuse every `CASE ... END`.
/// - `set`, `do`, `call`, `begin`, `close`, `move`, `load`, `key`, `share`, `no`
///   are excluded — they are ordinary English (so common in data), and they can
///   only ever be the *leading* keyword of a statement, which the allow-list in
///   [`classify_statement`] already refuses. Scanning for them would add
///   false-positives and no safety.
/// - `vacuum`, `refresh`, `cluster`, `reindex` are excluded for the same reason
///   (`'refresh'` is a very plausible column value), and are likewise already
///   caught as leading keywords.
const WRITE_WORDS_ANYWHERE: &[&str] = &[
    "insert", "update", "delete", "merge", "truncate", "drop", "alter", "create", "grant", "revoke",
];

#[derive(Debug, Clone, PartialEq, Eq)]
enum Tok {
    /// An unquoted word, lowercased. Only these are ever matched as keywords.
    Word(String),
    /// A `"quoted identifier"` — never a keyword, so it can never trip a match.
    QuotedIdent,
    /// A string literal (`'...'`, `E'...'`, `$tag$...$tag$`) — never a keyword,
    /// so `WHERE note = 'insert'` cannot false-positive.
    Literal,
    Punct(char),
}

pub fn classify(sql: &str) -> SqlKind {
    let mut tokens = match tokenize(sql) {
        Ok(tokens) => tokens,
        Err(reason) => return SqlKind::write(reason),
    };

    while matches!(tokens.last(), Some(Tok::Punct(';'))) {
        tokens.pop();
    }

    if tokens.is_empty() {
        return SqlKind::write("the statement is empty");
    }

    // A `;` left anywhere else means several statements were sent as one. The
    // extended protocol (`connection.query`) rejects these anyway, but refusing
    // here gives a clear message instead of a driver error — and keeps the hole
    // shut if this is ever refactored onto `simple_query`.
    if tokens.iter().any(|t| matches!(t, Tok::Punct(';'))) {
        return SqlKind::write(
            "several statements were sent in one request; send exactly one statement",
        );
    }

    let kind = classify_statement(&tokens);

    // Real writes are named precisely by classify_statement, so run the blunt
    // scan only as a veto over something that already parsed as a read.
    if kind.is_write() {
        return kind;
    }

    if let Some(word) = raw_text_mentions_write_word(sql) {
        return SqlKind::write(format!(
            "the text contains the word '{}'. It parses as a read-only statement, so this may \
             well be a false alarm (a string literal or a comment) — but this server errs on the \
             side of caution and asks for write access rather than deciding it is harmless. \
             Rephrase to avoid the word, or ask the user to grant write access",
            word.to_uppercase()
        ));
    }

    kind
}

/// Scans the raw SQL — comments and literals included — for any word in
/// [`WRITE_WORDS_ANYWHERE`].
///
/// Matches whole words only, where a "word" is a maximal run of alphanumerics
/// and underscores. So `delete_flag` and `updated_users` are single runs and do
/// **not** match, while `note = 'insert'` yields the run `insert` and does.
fn raw_text_mentions_write_word(sql: &str) -> Option<&'static str> {
    let mut word = String::new();

    // A trailing space flushes the final run without duplicating the check.
    for c in sql.chars().chain(std::iter::once(' ')) {
        if c.is_alphanumeric() || c == '_' {
            word.extend(c.to_lowercase());
            continue;
        }

        if !word.is_empty() {
            if let Some(found) = WRITE_WORDS_ANYWHERE.iter().find(|w| **w == word) {
                return Some(found);
            }
            word.clear();
        }
    }

    None
}

fn classify_statement(tokens: &[Tok]) -> SqlKind {
    // `(SELECT 1)` is a valid statement.
    let mut start = 0;
    while matches!(tokens.get(start), Some(Tok::Punct('('))) {
        start += 1;
    }

    let head = match tokens.get(start) {
        Some(Tok::Word(word)) => word.as_str(),
        _ => {
            return SqlKind::write("the statement does not start with a recognised SQL keyword");
        }
    };

    match head {
        "select" | "with" | "table" | "values" => classify_query_body(tokens, head),
        "show" => SqlKind::Read,
        "explain" => classify_explain(tokens, start + 1),
        other => match describe_write_statement(other) {
            Some(reason) => SqlKind::write(reason),
            // The allow-list's whole point: unknown means refused.
            None => SqlKind::write(format!(
                "'{}' is not a recognised read-only statement",
                other.to_uppercase()
            )),
        },
    }
}

/// Validates a `SELECT` / `WITH` / `TABLE` / `VALUES` body. Reaching here means
/// the head looks read-only; these checks catch the ways such a statement can
/// still write.
fn classify_query_body(tokens: &[Tok], head: &str) -> SqlKind {
    let mut depth: i32 = 0;

    for (index, token) in tokens.iter().enumerate() {
        match token {
            Tok::Punct('(') => depth += 1,
            Tok::Punct(')') => depth -= 1,
            Tok::Word(word) => {
                // `WITH x AS (INSERT INTO t VALUES (1) RETURNING *) SELECT * FROM x`
                // is a full write whose first keyword is WITH. Scan at every
                // depth, not just the head.
                if DATA_MODIFYING.contains(&word.as_str()) {
                    return SqlKind::write(format!(
                        "the statement contains a data-modifying {} inside a {}",
                        word.to_uppercase(),
                        head.to_uppercase()
                    ));
                }

                // `SELECT * INTO new_table FROM t` creates a table — it is
                // `CREATE TABLE AS` wearing a SELECT's clothes.
                if depth == 0 && word == "into" {
                    return SqlKind::write(
                        "SELECT ... INTO creates a new table; use a plain SELECT instead",
                    );
                }

                // `FOR UPDATE` / `FOR NO KEY UPDATE` / `FOR SHARE` / `FOR KEY SHARE`
                // take row locks. A pure read never needs them. Checked at every
                // depth: a locking clause is legal inside a CTE too.
                //
                // The keyword after `FOR` is what disambiguates this from the
                // unrelated `substring(x FROM 1 FOR 2)`, where `FOR` is followed
                // by a number.
                if word == "for" {
                    if let Some(Tok::Word(next)) = tokens.get(index + 1) {
                        if matches!(next.as_str(), "update" | "share" | "no" | "key") {
                            return SqlKind::write(
                                "a FOR UPDATE/FOR SHARE locking clause is not a read-only query",
                            );
                        }
                    }
                }

                if SIDE_EFFECT_FUNCTIONS.contains(&word.as_str())
                    && matches!(tokens.get(index + 1), Some(Tok::Punct('(')))
                {
                    return SqlKind::write(format!(
                        "{}() has side effects outside a read-only query",
                        word
                    ));
                }
            }
            _ => {}
        }
    }

    SqlKind::Read
}

/// `EXPLAIN ANALYZE <stmt>` **executes** `<stmt>` — allowing EXPLAIN blindly is a
/// complete write bypass. Accept EXPLAIN only without ANALYZE, then classify the
/// statement it wraps.
fn classify_explain(tokens: &[Tok], mut index: usize) -> SqlKind {
    // Parenthesised option list: EXPLAIN (ANALYZE, VERBOSE) SELECT ...
    if matches!(tokens.get(index), Some(Tok::Punct('('))) {
        let mut depth = 0;
        while index < tokens.len() {
            match &tokens[index] {
                Tok::Punct('(') => depth += 1,
                Tok::Punct(')') => {
                    depth -= 1;
                    if depth == 0 {
                        index += 1;
                        break;
                    }
                }
                Tok::Word(word) if word == "analyze" || word == "analyse" => {
                    return SqlKind::write(
                        "EXPLAIN ANALYZE actually executes the statement it wraps",
                    );
                }
                _ => {}
            }
            index += 1;
        }
    } else {
        // Bare option form: EXPLAIN ANALYZE VERBOSE SELECT ...
        while let Some(Tok::Word(word)) = tokens.get(index) {
            match word.as_str() {
                "analyze" | "analyse" => {
                    return SqlKind::write(
                        "EXPLAIN ANALYZE actually executes the statement it wraps",
                    );
                }
                "verbose" | "costs" | "settings" | "buffers" | "wal" | "timing" | "summary"
                | "format" | "generic_plan" | "memory" | "serialize" => index += 1,
                _ => break,
            }
        }
    }

    match tokens.get(index) {
        Some(_) => classify_statement(&tokens[index..]),
        None => SqlKind::write("EXPLAIN is missing the statement to explain"),
    }
}

/// Splits SQL into tokens, dropping comments and collapsing every literal and
/// quoted identifier into an opaque token. Everything downstream matches only on
/// `Tok::Word`, so keywords inside strings can never be mistaken for syntax.
///
/// Errors are deliberate: an unterminated literal or comment means we cannot
/// reason about the statement, and an unparseable statement is refused.
fn tokenize(sql: &str) -> Result<Vec<Tok>, String> {
    let chars: Vec<char> = sql.chars().collect();
    let mut tokens = Vec::new();
    let mut i = 0;

    while i < chars.len() {
        let c = chars[i];

        if c.is_whitespace() {
            i += 1;
            continue;
        }

        // Line comment: -- ... to end of line
        if c == '-' && chars.get(i + 1) == Some(&'-') {
            while i < chars.len() && chars[i] != '\n' {
                i += 1;
            }
            continue;
        }

        // Block comment. Postgres nests these, so track depth rather than
        // stopping at the first `*/`.
        if c == '/' && chars.get(i + 1) == Some(&'*') {
            let mut depth = 1;
            i += 2;
            while i < chars.len() && depth > 0 {
                if chars[i] == '/' && chars.get(i + 1) == Some(&'*') {
                    depth += 1;
                    i += 2;
                } else if chars[i] == '*' && chars.get(i + 1) == Some(&'/') {
                    depth -= 1;
                    i += 2;
                } else {
                    i += 1;
                }
            }
            if depth > 0 {
                return Err("the statement has an unterminated block comment".into());
            }
            continue;
        }

        // E'...' — same as '...' but backslashes escape.
        if (c == 'e' || c == 'E') && chars.get(i + 1) == Some(&'\'') {
            i = read_single_quoted(&chars, i + 1, true)?;
            tokens.push(Tok::Literal);
            continue;
        }

        if c == '\'' {
            i = read_single_quoted(&chars, i, false)?;
            tokens.push(Tok::Literal);
            continue;
        }

        if c == '"' {
            i = read_double_quoted(&chars, i)?;
            tokens.push(Tok::QuotedIdent);
            continue;
        }

        // $tag$ ... $tag$ — but `$1` is a bind parameter, not a dollar quote.
        if c == '$' {
            if let Some((tag_len, body_start)) = read_dollar_tag(&chars, i) {
                let closing: String = chars[i..body_start].iter().collect();
                match find_subslice(&chars, body_start, &closing) {
                    Some(end) => {
                        i = end + tag_len;
                        tokens.push(Tok::Literal);
                        continue;
                    }
                    None => {
                        return Err("the statement has an unterminated dollar-quoted string".into());
                    }
                }
            }
            tokens.push(Tok::Punct('$'));
            i += 1;
            continue;
        }

        if c.is_alphabetic() || c == '_' {
            let start = i;
            while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '_' || chars[i] == '$')
            {
                i += 1;
            }
            let word: String = chars[start..i].iter().collect();
            tokens.push(Tok::Word(word.to_lowercase()));
            continue;
        }

        if c.is_numeric() {
            while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '.') {
                i += 1;
            }
            tokens.push(Tok::Literal);
            continue;
        }

        tokens.push(Tok::Punct(c));
        i += 1;
    }

    Ok(tokens)
}

/// Returns the index just past the closing quote.
fn read_single_quoted(chars: &[char], start: usize, escapes: bool) -> Result<usize, String> {
    let mut i = start + 1;
    while i < chars.len() {
        let c = chars[i];
        if escapes && c == '\\' {
            i += 2;
            continue;
        }
        if c == '\'' {
            // '' inside a string is a literal quote, not the end.
            if chars.get(i + 1) == Some(&'\'') {
                i += 2;
                continue;
            }
            return Ok(i + 1);
        }
        i += 1;
    }
    Err("the statement has an unterminated string literal".into())
}

fn read_double_quoted(chars: &[char], start: usize) -> Result<usize, String> {
    let mut i = start + 1;
    while i < chars.len() {
        if chars[i] == '"' {
            if chars.get(i + 1) == Some(&'"') {
                i += 2;
                continue;
            }
            return Ok(i + 1);
        }
        i += 1;
    }
    Err("the statement has an unterminated quoted identifier".into())
}

/// At a `$`, recognises a dollar-quote opener. Returns `(tag_len, body_start)`
/// where `tag_len` counts the whole `$tag$` delimiter.
fn read_dollar_tag(chars: &[char], start: usize) -> Option<(usize, usize)> {
    let mut i = start + 1;
    while i < chars.len() && (chars[i].is_alphanumeric() || chars[i] == '_') {
        i += 1;
    }
    if chars.get(i) != Some(&'$') {
        return None;
    }
    let tag: String = chars[start + 1..i].iter().collect();
    // `$1$` would tokenize as a tag of "1"; a real tag never starts with a digit.
    if !tag.is_empty() && !(tag.starts_with(|c: char| c.is_alphabetic() || c == '_')) {
        return None;
    }
    Some((i + 1 - start, i + 1))
}

fn find_subslice(chars: &[char], from: usize, needle: &str) -> Option<usize> {
    let needle: Vec<char> = needle.chars().collect();
    if needle.is_empty() || from + needle.len() > chars.len() {
        return None;
    }
    (from..=chars.len() - needle.len()).find(|&i| chars[i..i + needle.len()] == needle[..])
}

#[cfg(test)]
mod tests {
    use super::*;

    fn is_read(sql: &str) -> bool {
        matches!(classify(sql), SqlKind::Read)
    }

    #[test]
    fn plain_reads_are_allowed() {
        assert!(is_read("SELECT * FROM users"));
        assert!(is_read("  select 1  "));
        assert!(is_read("SELECT count(*) FROM users WHERE id > 10"));
        assert!(is_read("WITH x AS (SELECT 1 AS a) SELECT * FROM x"));
        assert!(is_read("TABLE users"));
        assert!(is_read("VALUES (1), (2)"));
        assert!(is_read("SHOW search_path"));
        assert!(is_read("(SELECT 1)"));
        assert!(is_read("SELECT * FROM users;"));
        assert!(is_read("EXPLAIN SELECT * FROM users"));
        assert!(is_read("EXPLAIN (COSTS false) SELECT * FROM users"));
    }

    #[test]
    fn writes_are_blocked() {
        for sql in [
            "INSERT INTO users (id) VALUES (1)",
            "UPDATE users SET name = 'x'",
            "DELETE FROM users",
            "MERGE INTO t USING s ON t.id = s.id WHEN MATCHED THEN DELETE",
            "TRUNCATE users",
            "DROP TABLE users",
            "CREATE TABLE t (id int)",
            "ALTER TABLE t ADD COLUMN x int",
            "GRANT SELECT ON t TO bob",
            "REVOKE SELECT ON t FROM bob",
            "COPY t FROM '/tmp/x.csv'",
            "COPY t TO '/tmp/x.csv'",
            "CALL do_thing()",
            "DO $$ BEGIN PERFORM 1; END $$",
            "VACUUM FULL users",
            "REFRESH MATERIALIZED VIEW mv",
            "SET ROLE postgres",
            "RESET ALL",
            "BEGIN",
            "COMMIT",
            "DECLARE c CURSOR FOR SELECT 1",
            "PREPARE p AS INSERT INTO t VALUES (1)",
            "EXECUTE p",
            "LOCK TABLE t",
            "CHECKPOINT",
        ] {
            assert!(classify(sql).is_write(), "should be blocked: {}", sql);
        }
    }

    #[test]
    fn data_modifying_cte_is_blocked() {
        // The classic bypass: the statement leads with WITH, so a head-only
        // allow-list would wave it through.
        assert!(
            classify("WITH x AS (INSERT INTO t VALUES (1) RETURNING *) SELECT * FROM x").is_write()
        );
        assert!(classify("WITH x AS (DELETE FROM t RETURNING *) SELECT * FROM x").is_write());
        assert!(classify("WITH x AS (UPDATE t SET a = 1 RETURNING *) SELECT * FROM x").is_write());
    }

    #[test]
    fn select_into_is_blocked() {
        assert!(classify("SELECT * INTO new_table FROM users").is_write());
    }

    #[test]
    fn explain_analyze_is_blocked() {
        // ANALYZE really executes the wrapped statement.
        assert!(classify("EXPLAIN ANALYZE INSERT INTO t VALUES (1)").is_write());
        assert!(classify("EXPLAIN (ANALYZE) INSERT INTO t VALUES (1)").is_write());
        assert!(classify("EXPLAIN (ANALYZE true, VERBOSE) SELECT 1").is_write());
        assert!(classify("EXPLAIN ANALYZE SELECT 1").is_write());
        // ...and an EXPLAIN of a write is still a write even without ANALYZE.
        assert!(classify("EXPLAIN INSERT INTO t VALUES (1)").is_write());
    }

    #[test]
    fn multi_statement_is_blocked() {
        assert!(classify("SELECT 1; DROP TABLE users").is_write());
        // A trailing semicolon is just punctuation.
        assert!(!classify("SELECT 1 ; ").is_write());
    }

    #[test]
    fn locking_clause_is_blocked() {
        assert!(classify("SELECT * FROM t FOR UPDATE").is_write());
        assert!(classify("SELECT * FROM t FOR NO KEY UPDATE").is_write());
        assert!(classify("SELECT * FROM t FOR SHARE").is_write());
        // A locking clause is legal inside a CTE, so depth must not matter.
        assert!(classify("WITH x AS (SELECT * FROM t FOR UPDATE) SELECT * FROM x").is_write());
    }

    #[test]
    fn for_in_substring_is_not_a_locking_clause() {
        // `FOR` here is followed by a number, not UPDATE/SHARE.
        assert!(is_read("SELECT substring(name FROM 1 FOR 2) FROM t"));
    }

    #[test]
    fn write_words_are_refused_even_inside_literals() {
        // Deliberate over-blocking: these only read, but mentioning a write verb
        // is enough to require the window. Predictable beats clever.
        assert!(classify("SELECT * FROM t WHERE note = 'insert'").is_write());
        assert!(classify("SELECT * FROM t WHERE note = 'drop table users'").is_write());
        assert!(classify(r#"SELECT "insert" FROM t"#).is_write());
        assert!(classify("SELECT 'it''s an update' AS x").is_write());
        assert!(classify("SELECT * FROM t -- update this later").is_write());
        assert!(classify("SELECT $$insert into t$$ AS x").is_write());
        // The realistic false positive, accepted knowingly: an audit-log read.
        assert!(classify("SELECT * FROM audit WHERE action IN ('create','delete')").is_write());
    }

    #[test]
    fn write_words_embedded_in_identifiers_still_read() {
        // A word is a maximal run of alphanumerics/underscores, so these are the
        // single runs `updated_users` / `delete_flag` — not `update` / `delete`.
        assert!(is_read("SELECT * FROM updated_users"));
        assert!(is_read("SELECT delete_flag FROM t"));
        assert!(is_read("SELECT * FROM user_insert_log"));
        assert!(is_read("SELECT created_at FROM t ORDER BY created_at"));
        assert!(is_read("SELECT delete_flag FROM updated_users"));
    }

    #[test]
    fn common_sql_words_are_not_in_the_blunt_scan() {
        // `END` must never be scanned for: it would refuse every CASE expression.
        assert!(is_read(
            "SELECT CASE WHEN x > 1 THEN 'big' ELSE 'small' END FROM t"
        ));
        // Ordinary English that happens to be a leading-keyword elsewhere.
        assert!(is_read("SELECT * FROM t WHERE answer = 'no'"));
        assert!(is_read("SELECT * FROM tokens WHERE kind = 'refresh'"));
        assert!(is_read("SELECT * FROM jobs WHERE state = 'set'"));
    }

    #[test]
    fn comments_are_stripped() {
        assert!(is_read("/* comment */ SELECT 1"));
        assert!(is_read("-- comment\nSELECT 1"));
        // Postgres nests block comments.
        assert!(is_read("/* /* nested */ */ SELECT 1"));
        assert!(classify("/* hi */ INSERT INTO t VALUES (1)").is_write());
        // A `--` inside a string is not a comment.
        assert!(is_read("SELECT '--not a comment' AS x"));
    }

    #[test]
    fn side_effect_functions_are_blocked() {
        assert!(classify("SELECT nextval('my_seq')").is_write());
        assert!(classify("SELECT pg_read_file('/etc/passwd')").is_write());
        assert!(classify("SELECT lo_export(1, '/tmp/x')").is_write());
        // ...but a column merely named like one is fine.
        assert!(is_read("SELECT nextval FROM t"));
    }

    #[test]
    fn unparseable_input_fails_closed() {
        assert!(classify("").is_write());
        assert!(classify("   ").is_write());
        assert!(classify("SELECT 'unterminated").is_write());
        assert!(classify("/* unterminated SELECT 1").is_write());
        assert!(classify("WAT IS THIS").is_write());
    }

    #[test]
    fn dollar_quoted_strings_are_tokenized_as_literals() {
        // The tokenizer keeps a dollar-quoted body opaque so its contents can
        // never be mistaken for syntax...
        assert!(is_read("SELECT $$hello world$$ AS x"));
        assert!(is_read("SELECT $tag$some text$tag$ AS x"));
        // ...while the blunt raw scan still vetoes one that names a write verb.
        assert!(classify("SELECT $$insert into t$$ AS x").is_write());
        // A bind parameter is not a dollar quote.
        assert!(is_read("SELECT * FROM t WHERE id = $1"));
    }
}
